### PR TITLE
Add supported networks file

### LINKED ISSUE #43: Create JSON file with supported networks
To help the integration with docs and automated tools that consume information from this repository.
Include chain, chainid and scanner (RPC is desired, but too specific).

### PR DESCRIPTION
**Pull request by jubeira**
# Description

Add small JSON descriptor for supported networks.
This is to support documentation automation. Endpoints not included, since there are many options for each chain (both public and permissioned).

## Type of change

- [ ] Bug fix 
- [ ] New feature 
- [ ] Breaking change 
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [x] Documentation or wording changes
- [ ] Other

## Checklist:

- [x] The diff is legible and has no extraneous changes
- N/A Complex code has been commented, including external interfaces
- N/A Tests are included for all code paths
- [x] The base branch is either `master`, or there's a description of how to merge

## Issue Resolution

Closes #43

### CODE REVIEW

**Comment by jubeira** [comment]
@Tritium-VLK PTAL

**Comment by EndymionJkb** [comment]
We're maintaining this manually, and not using it ourselves for anything, right?

I'll add a section to the "deploying new networks" doc to remind us to keep this file up-to-date.

**Comment by jubeira** [comment]
> We're maintaining this manually, and not using it ourselves for anything, right?

Yes, I don't think adding CI checks for this is worth it.
Even now that we are adding networks more often, it's still rather infrequent.

We are not using it; it's just descriptive.

**Review by EndymionJkb — APPROVED** [review]
Verified all the chain ids and explorers (and added to our docs)

**Pull request merged**
